/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import com.mycompany.prueba.AFD;
import com.mycompany.prueba.Analizador;
import com.mycompany.prueba.Buscador;
import com.mycompany.prueba.Lector;
import com.mycompany.prueba.Reporte;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.Desktop;
import java.io.File;

/**
 *
 * @author abner
 */


public class Principal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Principal.class.getName());
    private Analizador analizador;
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        configurarTablas();
        configurarInterfaz();
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        JPContenedor = new javax.swing.JPanel();
        JPbotones = new javax.swing.JPanel();
        JBtnReportes = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        JPtexto = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        JPEncabezado = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        JPTokens = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaTokens = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        JPErrores = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaErrores = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        JPEstadisticas = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tablaEstadisticas = new javax.swing.JTable();
        JPDatos = new javax.swing.JPanel();
        JLTotalErrores = new javax.swing.JLabel();
        JLTotalLineas = new javax.swing.JLabel();
        JLTotalTokens = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JPContenedor.setBackground(new java.awt.Color(0, 0, 0));

        JPbotones.setBackground(new java.awt.Color(0, 0, 0));

        JBtnReportes.setText("Exportar Reporte");
        JBtnReportes.addActionListener(this::JBtnReportesActionPerformed);

        jButton2.setText("Cargar Archivo");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jButton3.setText("AFD");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        jButton5.setText("Guardar");
        jButton5.addActionListener(this::jButton5ActionPerformed);

        jButton6.setText("Salir");
        jButton6.addActionListener(this::jButton6ActionPerformed);

        javax.swing.GroupLayout JPbotonesLayout = new javax.swing.GroupLayout(JPbotones);
        JPbotones.setLayout(JPbotonesLayout);
        JPbotonesLayout.setHorizontalGroup(
            JPbotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPbotonesLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(JPbotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(JPbotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JBtnReportes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        JPbotonesLayout.setVerticalGroup(
            JPbotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPbotonesLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton5)
                .addGap(18, 18, 18)
                .addComponent(JBtnReportes)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(jButton6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        JPtexto.setBackground(new java.awt.Color(0, 0, 0));

        jButton4.setBackground(new java.awt.Color(204, 204, 204));
        jButton4.setForeground(new java.awt.Color(0, 0, 0));
        jButton4.setText("Analizar");
        jButton4.addActionListener(this::jButton4ActionPerformed);

        javax.swing.GroupLayout JPtextoLayout = new javax.swing.GroupLayout(JPtexto);
        JPtexto.setLayout(JPtextoLayout);
        JPtextoLayout.setHorizontalGroup(
            JPtextoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPtextoLayout.createSequentialGroup()
                .addContainerGap(247, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(230, 230, 230))
        );
        JPtextoLayout.setVerticalGroup(
            JPtextoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPtextoLayout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addContainerGap())
        );

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("               Datos obntenidos del analisis");

        JPEncabezado.setBackground(new java.awt.Color(51, 51, 51));

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("PROMPTZAL");

        javax.swing.GroupLayout JPEncabezadoLayout = new javax.swing.GroupLayout(JPEncabezado);
        JPEncabezado.setLayout(JPEncabezadoLayout);
        JPEncabezadoLayout.setHorizontalGroup(
            JPEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPEncabezadoLayout.createSequentialGroup()
                .addGap(572, 572, 572)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JPEncabezadoLayout.setVerticalGroup(
            JPEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPEncabezadoLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        jTextArea1.setBackground(new java.awt.Color(255, 255, 255));
        jTextArea1.setColumns(20);
        jTextArea1.setForeground(new java.awt.Color(0, 0, 0));
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        JPTokens.setBackground(new java.awt.Color(0, 255, 255));

        tablaTokens.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Lexema", "Tipo", "Fila", "Columna"
            }
        ));
        jScrollPane3.setViewportView(tablaTokens);

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("TOKENS");

        jLabel4.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("TOKENS");

        javax.swing.GroupLayout JPTokensLayout = new javax.swing.GroupLayout(JPTokens);
        JPTokens.setLayout(JPTokensLayout);
        JPTokensLayout.setHorizontalGroup(
            JPTokensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPTokensLayout.createSequentialGroup()
                .addGroup(JPTokensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPTokensLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JPTokensLayout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(JPTokensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JPTokensLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        JPTokensLayout.setVerticalGroup(
            JPTokensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPTokensLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(JPTokensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JPTokensLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        JPErrores.setBackground(new java.awt.Color(0, 204, 102));

        tablaErrores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Lexema", "Tipo", "Fila", "Columna"
            }
        ));
        jScrollPane4.setViewportView(tablaErrores);

        jLabel5.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("ERRORES");

        javax.swing.GroupLayout JPErroresLayout = new javax.swing.GroupLayout(JPErrores);
        JPErrores.setLayout(JPErroresLayout);
        JPErroresLayout.setHorizontalGroup(
            JPErroresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPErroresLayout.createSequentialGroup()
                .addGroup(JPErroresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPErroresLayout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addComponent(jLabel5))
                    .addGroup(JPErroresLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JPErroresLayout.setVerticalGroup(
            JPErroresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPErroresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        JPEstadisticas.setBackground(new java.awt.Color(102, 204, 0));
        JPEstadisticas.setForeground(new java.awt.Color(102, 204, 0));

        jLabel6.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("ESTADÍSTICAS");

        tablaEstadisticas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tipo", "Cantidad"
            }
        ));
        jScrollPane5.setViewportView(tablaEstadisticas);

        javax.swing.GroupLayout JPEstadisticasLayout = new javax.swing.GroupLayout(JPEstadisticas);
        JPEstadisticas.setLayout(JPEstadisticasLayout);
        JPEstadisticasLayout.setHorizontalGroup(
            JPEstadisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPEstadisticasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(172, 172, 172))
            .addGroup(JPEstadisticasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JPEstadisticasLayout.setVerticalGroup(
            JPEstadisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPEstadisticasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        JPDatos.setBackground(new java.awt.Color(102, 102, 102));

        JLTotalErrores.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        JLTotalErrores.setForeground(new java.awt.Color(255, 255, 255));
        JLTotalErrores.setText("Total Errores:");

        JLTotalLineas.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        JLTotalLineas.setForeground(new java.awt.Color(255, 255, 255));
        JLTotalLineas.setText("Total Lineas:");

        JLTotalTokens.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        JLTotalTokens.setForeground(new java.awt.Color(255, 255, 255));
        JLTotalTokens.setText("Total Tokens:");

        javax.swing.GroupLayout JPDatosLayout = new javax.swing.GroupLayout(JPDatos);
        JPDatos.setLayout(JPDatosLayout);
        JPDatosLayout.setHorizontalGroup(
            JPDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPDatosLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(JPDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(JLTotalTokens)
                    .addComponent(JLTotalErrores)
                    .addComponent(JLTotalLineas, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JPDatosLayout.setVerticalGroup(
            JPDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPDatosLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(JLTotalTokens)
                .addGap(18, 18, 18)
                .addComponent(JLTotalErrores)
                .addGap(18, 18, 18)
                .addComponent(JLTotalLineas)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("              Ingrese el texto para analizar");

        javax.swing.GroupLayout JPContenedorLayout = new javax.swing.GroupLayout(JPContenedor);
        JPContenedor.setLayout(JPContenedorLayout);
        JPContenedorLayout.setHorizontalGroup(
            JPContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPEncabezado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(JPContenedorLayout.createSequentialGroup()
                .addGroup(JPContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(JPContenedorLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(JPbotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(JPContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JPContenedorLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(JPContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(JPtexto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPane1))
                                .addGap(31, 31, 31)
                                .addComponent(JPDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPContenedorLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(87, 87, 87))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, JPContenedorLayout.createSequentialGroup()
                        .addComponent(JPTokens, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JPErrores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JPEstadisticas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41))
            .addGroup(JPContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JPContenedorLayout.createSequentialGroup()
                    .addGap(484, 484, 484)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(656, Short.MAX_VALUE)))
        );
        JPContenedorLayout.setVerticalGroup(
            JPContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPContenedorLayout.createSequentialGroup()
                .addComponent(JPEncabezado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JPContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPContenedorLayout.createSequentialGroup()
                        .addGap(0, 12, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(JPContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(JPContenedorLayout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JPtexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(JPDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(JPbotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JPContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(JPTokens, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JPErrores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(JPEstadisticas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9))
            .addGroup(JPContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JPContenedorLayout.createSequentialGroup()
                    .addGap(96, 96, 96)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(823, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JPContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        analizarTexto();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        guardarArchivo();
        System.out.println("ARchivo guardado");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        Buscador buscador = new Buscador();
        String ruta = buscador.seleccionarArchivo();

        if (ruta == null) {
            return;
        }

        try {

            String contenido = buscador.leerArchivo(ruta);
            jTextArea1.setText(contenido);

        } catch (IOException e) {

            JOptionPane.showMessageDialog(this,"No se pudo abrir el archivo:\n" + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void JBtnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnReportesActionPerformed
        
        if (analizador == null) {

            JOptionPane.showMessageDialog(this,"Primero debe analizar un archivo o texto.","No hay datos",JOptionPane.WARNING_MESSAGE);
            return;
        }

         try {

            Reporte reporte = new Reporte(analizador.getTokens(),analizador.getErrores());

            reporte.generarReporteTokens();
            reporte.generarReporteErrores();
            reporte.generarReporteEstadisticas();

            int opcion = JOptionPane.showConfirmDialog(this,"Los reportes fueron generados correctamente" + "¿Desea abrir los reportes?","Reportes generados",JOptionPane.YES_NO_OPTION,JOptionPane.INFORMATION_MESSAGE);
            
            if (opcion == JOptionPane.YES_OPTION) {

                abrirReporte("reporte_tokens.html");
                abrirReporte("reporte_errores.html");
                abrirReporte("reporte_estadisticas.html");
            }

        } catch (IOException e) {

            JOptionPane.showMessageDialog(this,"No se  generaron los reportes.\n\n" + e.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_JBtnReportesActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        
        int opcion = JOptionPane.showConfirmDialog(this,"¿Está seguro de que desea salir?","Salir",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);

        if (opcion == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
            try {

            AFD generador = new AFD();
            generador.generarAFD();

            int opcion = JOptionPane.showConfirmDialog(this,"El AFD se generó correctamente.\n\n" + "¿Desea abrir la imagen del AFD?", "AFD generado",JOptionPane.YES_NO_OPTION,JOptionPane.INFORMATION_MESSAGE);

            if (opcion == JOptionPane.YES_OPTION) {

                File imagen = new File("afd_promptzal.png");

                if (Desktop.isDesktopSupported() && Desktop.getDesktop().isSupported(Desktop.Action.OPEN)) {

                    Desktop.getDesktop().open(imagen);

                } else {

                    JOptionPane.showMessageDialog(this,"No se puede abrir automáticamente la imagen.\n", "Abrir AFD", JOptionPane.INFORMATION_MESSAGE);
                }
            }

        } catch (IOException e) {

            JOptionPane.showMessageDialog(this,"No se pudo generar el AFD.\n\n"+ e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    //Métodos para los botones
    private void guardarArchivo() {

         Buscador buscador = new Buscador();
        javax.swing.JFileChooser explorador = new javax.swing.JFileChooser();
         javax.swing.filechooser.FileNameExtensionFilter filtro =new javax.swing.filechooser.FileNameExtensionFilter("Archivos PromptZal (*.pz)", "pz");
         explorador.setFileFilter(filtro);

        int opcion = explorador.showSaveDialog(this);

        if (opcion != javax.swing.JFileChooser.APPROVE_OPTION) {
            return;
        }

        java.io.File archivo = explorador.getSelectedFile();
        String ruta = archivo.getAbsolutePath();

        if (!ruta.toLowerCase().endsWith(".pz")) {
        ruta += ".pz";
        }

        try {

            buscador.guardarArchivo(ruta, jTextArea1.getText());

            JOptionPane.showMessageDialog(
                this,"Archivo guardado correctamente.", "Guardar", JOptionPane.INFORMATION_MESSAGE);

        } catch (IOException e) {

            JOptionPane.showMessageDialog(
                this,"No se pudo guardar el archivo:\n" + e.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void analizarTexto() {

        String contenido = jTextArea1.getText();

        if (contenido.trim().isEmpty()) {

            JOptionPane.showMessageDialog(this,"No hay texto para analizar.","Analizar",JOptionPane.WARNING_MESSAGE);

            return;
        }

        try {

            Lector lector = new Lector(contenido, true);
            analizador = new Analizador(lector);
            analizador.analizar();
            
            mostrarTokens();
            mostrarErrores();
            mostrarEstadisticas();
            mostrarResumen();

            System.out.println("ANALISIS TERMINADO");
            System.out.println("Tokens encontrados: " + analizador.getTokens().size());
            System.out.println("Errores encontrados: " + analizador.getErrores().size());
            lector.cerrar();

        } catch (IOException ex) {

            JOptionPane.showMessageDialog(this,"Ocurrió un error durante el análisis:\n" + ex.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void mostrarTokens() {

    DefaultTableModel modelo = (DefaultTableModel) tablaTokens.getModel();

    modelo.setRowCount(0);

    for (com.mycompany.prueba.Token token : analizador.getTokens()) {

            modelo.addRow(new Object[]{token.getNumero(),token.getLexema(),token.getTipo(),token.getFila(),token.getColumna()});
        }
    }
    
    private void mostrarErrores() {

        DefaultTableModel modelo = (DefaultTableModel) tablaErrores.getModel();
        modelo.setRowCount(0);

        for (com.mycompany.prueba.Error error : analizador.getErrores()) {

            modelo.addRow(new Object[]{error.getLexema(),error.getTipo(),error.getFila(),error.getColumna()});
        }   
    }
    
    private void mostrarEstadisticas() {

    DefaultTableModel modelo = (DefaultTableModel) tablaEstadisticas.getModel();

    modelo.setRowCount(0);

    int directivas = 0;
    int palabras_reservadas = 0;
    int comandos_ia = 0;
    int conectores = 0;
    int identificadores = 0;
    int cadenas = 0;
    int enteros = 0;
    int decimales = 0;
    int operadores = 0;
    int delimitadores = 0;
    int funciones = 0;
    int asignaciones = 0;
    int concatenaciones = 0;

    for (com.mycompany.prueba.Token token : analizador.getTokens()) {

        switch (token.getTipo()) {

            case DIRECTIVA:
                directivas++;
                break;

            case PALABRA_RESERVADA:
                palabras_reservadas++;
                break;

            case COMANDO_IA:
                comandos_ia++;
                break;

            case CONECTOR:
                conectores++;
                break;

            case IDENTIFICADOR:
                identificadores++;
                break;

            case CADENA:
                cadenas++;
                break;

            case ENTERO:
                enteros++;
                break;

            case DECIMAL:
                decimales++;
                break;

            case OPERADOR:
                operadores++;
                break;

            case DELIMITADOR:
                delimitadores++;
                break;

            case FUNCION:
                funciones++;
                break;

            case ASIGNACION:
                asignaciones++;
                break;

            case CONCATENACION:
                concatenaciones++;
                break;
                
        }
    }

    modelo.addRow(new Object[]{"DIRECTIVA", directivas});
    modelo.addRow(new Object[]{"PALABRA_RESERVADA", palabras_reservadas});
    modelo.addRow(new Object[]{"COMANDO_IA", comandos_ia});
    modelo.addRow(new Object[]{"CONECTOR", conectores});
    modelo.addRow(new Object[]{"IDENTIFICADOR", identificadores});
    modelo.addRow(new Object[]{"CADENA", cadenas});
    modelo.addRow(new Object[]{"ENTERO", enteros});
    modelo.addRow(new Object[]{"DECIMAL", decimales});
    modelo.addRow(new Object[]{"OPERADOR", operadores});
    modelo.addRow(new Object[]{"DELIMITADOR", delimitadores});
    modelo.addRow(new Object[]{"FUNCION", funciones});
    modelo.addRow(new Object[]{"ASIGNACION", asignaciones});
    modelo.addRow(new Object[]{"CONCATENACION", concatenaciones});
}
    
    private void mostrarResumen() {

        int total_tokens = analizador.getTokens().size();
        int total_errores = analizador.getErrores().size();
        int total_lineas = 1;
        String contenido = jTextArea1.getText();

        for (int i = 0; i < contenido.length(); i++) {

            if (contenido.charAt(i) == '\n') {
                total_lineas++;
            }
        }
        

        JLTotalTokens.setText("Total de tokens: " + total_tokens);
        JLTotalErrores.setText("Total de errores: " + total_errores);
        JLTotalLineas.setText("Total de líneas: " + total_lineas);
}
    
    
    private void configurarTablas() {

        java.awt.Color fondo_tabla =new java.awt.Color(30, 33, 40);
        java.awt.Color texto =new java.awt.Color(230, 230, 230);

        configurarTabla(tablaTokens,jScrollPane3,fondo_tabla,texto);
        configurarTabla(tablaErrores,jScrollPane4,fondo_tabla,texto);
        configurarTabla(tablaEstadisticas,jScrollPane5,fondo_tabla,texto);
    }

    private void configurarTabla(javax.swing.JTable tabla,javax.swing.JScrollPane scroll,java.awt.Color fondo,java.awt.Color texto) {

        // Tabla
        tabla.setBackground(fondo);
        tabla.setForeground(texto);

        // Área vacía del JScrollPane
        scroll.setBackground(fondo);
        scroll.getViewport().setBackground(fondo);

        // Altura de las filas
        tabla.setRowHeight(28);

        // Fuente
        tabla.setFont(new java.awt.Font("Segoe UI",java.awt.Font.PLAIN,13));

        // Color de selección
        tabla.setSelectionBackground(new java.awt.Color(108, 99, 255));
        tabla.setSelectionForeground(java.awt.Color.WHITE);

        // Encabezado
        tabla.getTableHeader().setBackground(new java.awt.Color(108, 99, 255));
        tabla.getTableHeader().setForeground(java.awt.Color.WHITE);
        tabla.getTableHeader().setFont(new java.awt.Font("Segoe UI",java.awt.Font.BOLD,13));

        // Altura del encabezado
        tabla.getTableHeader().setPreferredSize( new java.awt.Dimension(0, 32));
    }
    
    private void configurarInterfaz() {

        java.awt.Color fondo_oscuro =new java.awt.Color(30, 33, 40);
        java.awt.Color texto_claro =new java.awt.Color(230, 230, 230);

        // Área de texto
        jTextArea1.setBackground(fondo_oscuro);
        jTextArea1.setForeground(texto_claro);
        jTextArea1.setCaretColor(texto_claro);
        jTextArea1.setFont(new java.awt.Font("Segoe UI",java.awt.Font.PLAIN,14));
        jTextArea1.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));

        // Panel de datos
        JPDatos.setBackground(fondo_oscuro);
    }
    
    private void abrirReporte(String nombre_archivo) {

        try {

            File archivo = new File(nombre_archivo);

            if (!archivo.exists()) {

                JOptionPane.showMessageDialog(this,"No se encontró el archivo:\n"+ archivo.getAbsolutePath(),"Archivo no encontrado",JOptionPane.WARNING_MESSAGE);
                return;
            }

            if (Desktop.isDesktopSupported() && Desktop.getDesktop().isSupported(Desktop.Action.BROWSE)) {

                Desktop.getDesktop().browse( archivo.toURI());

            } else {

                JOptionPane.showMessageDialog(this,
                    "No se puede abrir automáticamente el navegador"+ archivo.getAbsolutePath(),"Abrir reporte",JOptionPane.INFORMATION_MESSAGE);
            }

        } catch (IOException e) {

            JOptionPane.showMessageDialog(this,"No se pudo abrir el reporte" + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBtnReportes;
    private javax.swing.JLabel JLTotalErrores;
    private javax.swing.JLabel JLTotalLineas;
    private javax.swing.JLabel JLTotalTokens;
    private javax.swing.JPanel JPContenedor;
    private javax.swing.JPanel JPDatos;
    private javax.swing.JPanel JPEncabezado;
    private javax.swing.JPanel JPErrores;
    private javax.swing.JPanel JPEstadisticas;
    private javax.swing.JPanel JPTokens;
    private javax.swing.JPanel JPbotones;
    private javax.swing.JPanel JPtexto;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTable tablaErrores;
    private javax.swing.JTable tablaEstadisticas;
    private javax.swing.JTable tablaTokens;
    // End of variables declaration//GEN-END:variables
}
